### ISSUE TITLE
Help Maceration Stack Controller

### ISSUE THREAD

**Issue by Ayutu** [draknyte1/MiscUtilities#6]
I try to build this multi block but i'm stuck with "Incomplete Structure." 
I tried many combinations. I can't find what i missing. :/
This is what i test in creative mode :

![creative test](https://cloud.githubusercontent.com/assets/15825690/17459635/f2ef373e-5c40-11e6-93ff-574629feba08.png)

ZPM Energy Hatch + Maintenance Hatch + ZPM Input bus + 3 ZPM Output bus + Controller and casing.

**Comment by draknyte1** [comment]
It requires 5 output Buses.
![2016-08-07_13 08 39](https://cloud.githubusercontent.com/assets/3060479/17460230/3e4f8b52-5ca0-11e6-9790-9d297c59a07b.png)
For whatever reason I've wrote the tooltip wrong. Fixed in next release, since it's only a typo I won't release a hotfix.
