### ISSUE TITLE
industrial centrifuge lacks spot to insert turbine

### ISSUE THREAD

**Issue by Sudoloo** [draknyte1/MiscUtilities#7]
as title says, i cannot find a way to insert the turbine to the industrial centrifuge. the multiblock has been formed, and issues have been solved, but i cannot insert a turbine anywhere. to list the things i have tried,
tungsten steel huge turbine,
iridium gearbox rotor
tungsten steel turbine blades
gas turbine blocks are varying descriptions,
 and the null turbines of every size through creative
i have tried inserting all of these into every area of which i can insert an item, and have yet to have it perform any process, 
additional information, everything was done at zpm for convenience sake, a texture pack was in use, gui scale was on normal. am i simply missing something?

**Comment by draknyte1** [comment]
It doesn't require one.
Textual error, already fixed in dev. 

Is centrifuge turned off in the config? It was originally by default.

**Comment by Sudoloo** [comment]
huh, i guess beyond reality must have changed it back. i suppose ill just kinda keep the thing until the pack updates then. thanks for the fast answer.

**Comment by draknyte1** [comment]
I'm not sure what versions currently in BR, I simply test against the latest public/dev relases and poke @leagris when needed to try push updates to BR users.

Latest release available here has the Centrifuge enabled by default, with a fixed tooltip and processing mechanics (It was buggy, hence the disabled message by default)
