### ISSUE TITLE
3x3 pickaxe mines a 5x5 area when looking down.

### ISSUE THREAD

**Issue by MaDmaxwell311** [draknyte1/MiscUtilities#9]
Title says it all. I could not remember the name of the item, sorry about that.

**Comment by draknyte1** [comment]
`if (FACING.equals("below") || FACING.equals("above")){
				DURABILITY_LOSS = 0;
				for(int i = -2; i < 3; i++) {
					for(int j = -2; j < 3; j++) {
						float dur = calculateDurabilityLoss(world, X + i, Y, Z + j);
						DURABILITY_LOSS = (DURABILITY_LOSS + calculateDurabilityLoss(world, X + i, Y, Z + j));	
						Utils.LOG_WARNING("Added Loss: "+dur);
						removeBlockAndDropAsItem(world, X + i, Y, Z + j, heldItem);
					}
				}
			}

			else if (FACING.equals("facingEast") || FACING.equals("facingWest")){
				DURABILITY_LOSS = 0;
				for(int i = -1; i < 2; i++) {
					for(int j = -1; j < 2; j++) {
						float dur = calculateDurabilityLoss(world, X, Y + i, Z + j);
						DURABILITY_LOSS = (DURABILITY_LOSS + calculateDurabilityLoss(world, X, Y + i, Z + j));
						Utils.LOG_WARNING("Added Loss: "+dur);
						removeBlockAndDropAsItem(world, X , Y + i, Z + j, heldItem);
					}
				}
			}

			else if (FACING.equals("facingNorth") || FACING.equals("facingSouth")){
				DURABILITY_LOSS = 0;
				for(int i = -1; i < 2; i++) {
					for(int j = -1; j < 2; j++) {
						float dur = calculateDurabilityLoss(world, X + j, Y + i, Z);
						DURABILITY_LOSS = (DURABILITY_LOSS + dur);
						Utils.LOG_WARNING("Added Loss: "+dur);
						removeBlockAndDropAsItem(world, X + j, Y + i, Z, heldItem);
					}
				}
			}`

  

Alright, I uhh, fixed this.
